#!/bin/bash

set -e -u

catalog=$(curl -s ${BROKER_URI:?required}/v2/catalog)
service_id=$(echo $catalog | jq -r ".services[0].id")
plan_id=$(echo $catalog | jq -r ".services[0].plans[0].id")

instance_id=etcd-$(date +"%s" | rev)
binding_id=bind-$(date +"%s" | rev)

info() {
  echo "$@ " >&2
}

create_instance() {
  set +x
  info creating service instance ${instance_id} for plan ${plan_id}
  set -x
  curl ${BROKER_URI}/v2/service_instances/${instance_id} \
       -XPUT \
       -d "{\"service_id\":\"${service_id}\",\"plan_id\":\"${plan_id}\"}" \
       >&2 || {
    echo "Couldn't create service instance"
    exit 1
  }
}

create_binding() {
  set +x
  info creating binding ${binding_id} for instance ${instance_id}
  set -x
  curl -sf ${BROKER_URI}/v2/service_instances/${instance_id}/service_bindings/${binding_id} \
    -XPUT \
    -d "{\"service_id\": \"${service_id}\", \"plan_id\": \"${plan_id}\"}" || {
    echo "Couldn't create instance binding"
    exit 1
  }
}

delete_binding() {
  set +x
  info deleting binding ${binding_id} for instance ${instance_id}
  set -x
  curl -f -XDELETE \
    ${BROKER_URI}/v2/service_instances/${instance_id}/service_bindings/${binding_id}\?service_id=${service_id}\&plan_id=${plan_id} || {
    echo "Couldn't delete instance binding"
    exit 1
  }
  set +x
}

delete_instance() {
  set +x
  info deleting instance ${instance_id}
  set -x
  curl -f -XDELETE \
    ${BROKER_URI}/v2/service_instances/${instance_id}\?service_id=${service_id}\&plan_id=${plan_id} || {
    echo "Couldn't delete instance"
    exit 1
  }
  set +x
}

create_instance
credentials=$(create_binding)
set +x

echo $credentials | jq -r .

uri=$(echo $credentials | jq -r ".credentials.uri")
if [[ "${uri}X" == "X" || "${uri}" == "null" ]]; then
  echo "Binding credentials missing 'uri' key"
  exit 1
fi

echo Setting value
curl $uri/hello -XPUT -d 'value=world'

echo Getting value
curl $uri/hello
value=$(curl -s $uri/hello | jq -r .node.value)
if [[ "${value}" != "world" ]]; then
  echo "Value retrived from $uri/hello should be 'world', was '${value}'"
  exit 1
fi

host=$(echo $credentials | jq -r ".credentials.host")
username=$(echo $credentials | jq -r ".credentials.username")
password=$(echo $credentials | jq -r ".credentials.password")
base_path=$(echo $credentials | jq -r ".credentials.base_path")

error_code=$(curl -s -u ${username}:${password} ${host}/v2/keys/not-allowed -XPUT -d 'value=try-this' | jq -r .errorCode)
if [[ "${error_code}" != "110" ]]; then
  echo "Expected errorCode 110 as shouldn't be allowed to access /not-allowed; got '${error_code}'"
  exit 1
fi

delete_binding
set +x
echo "access to /hello should now be denied"

error_code=$(curl -s $uri/hello | jq -r .errorCode)
if [[ "${error_code}" != "110" ]]; then
  echo "Expected errorCode 110 as shouldn't be allowed to access /hello anymore; got '${error_code}'"
  exit 1
fi

echo "creating new binding, with same binding ID"
old_password=$password
credentials=$(create_binding)
echo $credentials | jq -r .

uri=$(echo $credentials | jq -r ".credentials.uri")
if [[ "${uri}X" == "X" || "${uri}" == "null" ]]; then
  echo "Binding credentials missing 'uri' key"
  exit 1
fi
password=$(echo $credentials | jq -r ".credentials.password")
if [[ "${password}" == "${old_password}" ]]; then
  echo "Expecting new binding to have new password"
  exit 1
fi

echo "Getting value /hello again"
curl $uri/hello
value=$(curl -s $uri/hello | jq -r .node.value)
if [[ "${value}" != "world" ]]; then
  echo "Value retrived from $uri/hello should be 'world', was '${value}'"
  exit 1
fi

delete_binding
delete_instance

echo "User's /hello should now be deleted"
missing_value=$(curl -s ${ETCD_URI:?required}${base_path}/hello | jq -r .node.value)
if [[ "${missing_value}" != "null" ]]; then
  echo "Expecting that all data within ${base_path} has been deleted"
  exit 1
fi
